name: C/C++ CI

on: [push, pull_request, workflow_dispatch]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4.1.1
    
    - name: Set up C/C++ build
      run: sudo apt-get update && sudo apt-get install -y build-essential g++
      
    - name: Syntax Check
      run: g++ -c -Wall *.cpp
